server:
  port: 8083
spring:
  application:
    name: kenanai-share-file

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
    timeout: 5000
    retries: 0
  config-center:
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848