server:
  port: 9000

spring:
  application:
    name: kenanai-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kenanai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: KenanAI-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
    timeout: 5000
    retries: 0
  config-center:
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848

# JWT配置
jwt:
  # JWT密钥
  secret: kenanai-secret-key-for-jwt-token-signature-verification-and-generation
  # JWT过期时间（秒）
  expire: 86400
  # JWT头部
  header: Authorization

logging:
  level:
    com.kenanai: debug 